channels:
  - anaconda
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudnn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - scikit-learn
  - pytorch-lightning
  - tensorboard
  - nltk
  - pip
  - pip:
    - transformers==4.3.3
    - allennlp-models==2.1.0
    - allennlp==2.1.0
