channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudnn=7.6
  - cudatoolkit=10.2
  - scikit-learn=0.24
  - pytorch-gpu
  - tensorboard
  - nltk
  - pip
  - pip:
    - transformers==4.3.3
    - allennlp-models==2.1.0
    - allennlp==2.1.0

