#!/bin/bash

# Download one of the ELMO language models for training
mkdir elmo
model='large'
if [ $model = 'small' ]; then
  options_url="https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_options.json"
  weights_url="https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5"
  options_file="elmo/elmo_2x1024_128_2048cnn_1xhighway_options.json"
  weights_file="elmo/elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5"
elif [ $model = 'medium' ]; then
  options_url="https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_1xhighway/elmo_2x2048_256_2048cnn_1xhighway_options.json"
  weights_url="https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_1xhighway/elmo_2x2048_256_2048cnn_1xhighway_weights.hdf5"
  options_file="elmo/elmo_2x2048_256_2048cnn_1xhighway_options.json"
  weights_file="elmo/elmo_2x2048_256_2048cnn_1xhighway_weights.hdf5"
elif [ $model = 'large' ]; then
  options_url="https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway_5.5B/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json"
  weights_url="https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway_5.5B/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5"
  options_file="elmo/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json"
  weights_file="elmo/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5"
fi
wget $options_url -O $options_file
wget $weights_url -O $weights_file

CUDA_VISIBLE_DEVICES=0 python3 train_elmo_tagger.py \
  --options-file $options_file \
  --weights-file $weights_file \
  --train-file=data_train.pkl \
  --eval-file=data_valid.pkl \
  --test-file=data_test.pkl \
  --model-type=lstm --use-bilstm \
  --output-dir=elmo-pos-tagger-lstm-large \
  --train-batch-size=32 \
  --num-epochs=20 \
  --use-gpu